### ISSUE TITLE
Weekly Scrum - March 18 to March 24

### ISSUE THREAD

**Issue by gurveerdhindsa** [gurveerdhindsa/online-bookstore#70]

**Comment by gurveerdhindsa** [comment]
During this week, I began development of the admin view. I planned that a panel will popup upon clicking the edit button of a book. 

PR:
https://github.com/gurveerdhindsa/online-bookstore/pull/66

Issues:
https://github.com/gurveerdhindsa/online-bookstore/issues/59

**Comment by rohank07** [comment]
This week I wrote code for the admin side, in particular the endpoint for an admin to add a book and the test cases as well. 
PR 
#60 
Issues:
#61
For next week, I will look at refactoring code and doing some integration testing.

**Comment by AbubakarAbdulsalam** [comment]
This week i worked on the admin endpoints, in particular the endpoints that allows for the updating and deletion of books as well as the corresponding test cases for those scenarios.

PR
#62
