### ISSUE TITLE
Weekly Scrum - March 25 to April 1

### ISSUE THREAD

**Issue by gurveerdhindsa** [gurveerdhindsa/online-bookstore#71]

**Comment by gurveerdhindsa** [comment]
During this week, I finished the admin view and displaying recommendations for users. 

PR links: 
https://github.com/gurveerdhindsa/online-bookstore/pull/69

Issue links:
https://github.com/gurveerdhindsa/online-bookstore/issues/67

**Comment by rohank07** [comment]
This week I made minor code changes and resolved errors on the backend side. Wrapped up the course project and updated the ReadMe and project deliverables.

**Comment by AbubakarAbdulsalam** [comment]
Fixed errors with test cases and made changes to certain data access methods along with changes to the parameter types of certain endpoints.

PR
#68
